#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
  This script loads optional roles from 'Roles.yaml', provided such a file
  exists and contains valid YAML. Puppet invokes this script as its External
  Node Classifier. See <http://docs.puppetlabs.com/guides/external_nodes.html>
  for details.

"""
from __future__ import print_function

import io
import sys
import yaml


empty = dict(classes=[])

try:
    with io.open('/vagrant/Roles.yaml', encoding='utf-8') as f:
        manifest = yaml.load(f)
    if not isinstance(manifest, dict):
        raise ValueError('Manifest document must be a mapping.')
    if not isinstance(manifest.get('classes'), list):
        raise ValueError('Manifest document must define a "classes" key that '
                         'has a list of classes as its value.')
except IOError:
    # OK -- No Roles.yaml file.
    print(yaml.dump(empty))
except (AssertionError, TypeError, ValueError, yaml.YAMLError) as e:
    print('Roles.yaml does not contain a valid YAML manifest.',
          'Please fix the file, or delete it to have it regenerated.',
          'Error: %s' % e, sep='\n', file=sys.stderr)
    sys.exit(1)
else:
    print(yaml.dump(manifest))
