#!/usr/bin/env bash
# Command run in VM for `vagrant import-dump`
. /etc/profile.d/set_MW_INSTALL_PATH.sh
cd "$MW_INSTALL_PATH"
/usr/local/bin/mwscript importDump.php -- "/vagrant/$1"
/usr/local/bin/mwscript rebuildrecentchanges.php
