#!/bin/bash
. /etc/profile.d/puppet-managed/set_mw_install_path.sh

set -u
declare -a errors

function pull {
  echo
  branch=$(expr $(git symbolic-ref HEAD) : 'refs/heads/\(.*\)')
  err=''
  if [ -n "$branch" ]; then
    remote=$(git config branch.$branch.remote)
    if [ -n "$remote" ]; then
        url=$(git config --get remote.$remote.url)
        if [[ $url == ssh://* ]]; then
            # Convert remote git url from ssh:// to anonymous https://
            tempurl=$(echo $url | sed -e 's!ssh://[^@]\+@!https://!g' -e 's!:29418!/r!g')
            git pull $tempurl
        else
            git pull
        fi
        if [ $? -ne 0 ]; then
          err="GIT PULL failed in $(pwd) for branch '$branch'"
        fi
    else
        err="Remote not found in $(pwd) for branch '$branch'"
    fi
  else
    err="Unable to get current branch in $(pwd)"
  fi

  if [ -n "$err" ]; then
    echo -e "\e[1;31m ***** $err\e[0m"
    errors+=("$err")
  fi
}

cd "$MW_INSTALL_PATH"
pull

for f in extensions/*
do
 if [[ -d $f ]]; then
  pushd $f > /dev/null
  pull
  popd > /dev/null
 fi
done

php maintenance/update.php --quick

if [ ${#errors[@]} -ne 0 ]; then
  echo
  echo -e "\e[1;31m ************* Errors ***********\e[0m"
  printf -- '* %s\n' "${errors[@]}"
fi
