# == Class: role::trafficserver
#
# Installs an Apache Traffic Server instance, which only caches thumbnails
# generated by thumbor.
#
class role::trafficserver {
    include ::role::thumbor
    include ::trafficserver

    mediawiki::settings { 'trafficserver':
        values => {
            'wgUploadBaseUrl' => 'http://127.0.0.1:6090',
            'wgUseSquid'      => true,
            'wgSquidServers'  => [ '127.0.0.1:6090' ],
        }
    }
}
