#!/bin/bash
# Part of puppet/manifests/roles/apparmor.pp
# Check and see if apparmor has denied anything recently.

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

REGEX="apparmor=\"DENIED\""
LOGFILE=/var/log/syslog
DCOUNT=$(grep -c "$REGEX" $LOGFILE)

echo "There are $DCOUNT instances of AppArmor denying applications in $LOGFILE"
if [[ $DCOUNT > 0 ]]; then
    echo "Most recent entries:"
    grep "$REGEX" $LOGFILE | tail
fi
