#!/bin/bash

set -e

ES_VERSION=$(dpkg -l elasticsearch 2>/dev/null | awk '$2 == "elasticsearch" { print $3 }')
if [ -z "$ES_VERSION" ]; then
  echo "Elasticsearch not installed"
  exit 1
fi

ACTION="$1"
PLUGIN_NAME="$2"
if [ -z "$3" ]; then
  INSTALL_ARGS="$PLUGIN_NAME"
else
  # In elasticsearch 2 this is group/title, which elasticsearch will use
  # to magic up some urls. in elasticsearch 5 we will have to provide our
  # own urls
  INSTALL_ARGS="$3/$ES_VERSION"
fi

PLUGIN_DIR="/usr/share/elasticsearch/plugins/${PLUGIN_NAME}"
if [ -d "$PLUGIN_DIR" ]; then
  PLUGIN_INSTALLED="yes"
  PLUGIN_VERSION=$(awk -F '=' '$1 == "elasticsearch.version" { print $2 }' < "$PLUGIN_DIR/plugin-descriptor.properties")
else
  PLUGIN_INSTALLED="no"
  PLUGIN_VERSION=""
fi


case "$ACTION" in
  check)
    # Check if install is required, used as the 'unless' case in puppet exec
    if [ "$PLUGIN_INSTALLED" = "yes" -a "$ES_VERSION" = "$PLUGIN_VERSION" ]; then
      exit 0
    else
      exit 1
    fi
    ;;

  install)
    if [ "$PLUGIN_INSTALLED" = "yes" -a "$ES_VERSION" = "$PLUGIN_VERSION" ]; then
      echo "$PLUGIN_NAME already installed with version $PLUGIN_VERSION"
    else
      if [ "$PLUGIN_INSTALLED" = "yes" ]; then
        echo "Pruning old version ($PLUGIN_VERSION) of $PLUGIN_NAME"
        /usr/share/elasticsearch/bin/plugin remove "$PLUGIN_NAME"
      fi

      # We need to delete all old plugins before trying to install a new
      # one, "bin/plugin install" will simply fail if an unsupported one
      # is found in the plugins directory.
      find /usr/share/elasticsearch/plugins -mindepth 1 -maxdepth 1 -type d \
        '!' '(' -exec test -e '{}/plugin-descriptor.properties' ';' -a \
                -exec egrep -q "(^elasticsearch.version=${ES_VERSION}|^site=true)" \
                               '{}/plugin-descriptor.properties' ';' \
            ')' \
        -exec sh -c '/usr/share/elasticsearch/bin/plugin remove `basename {}`' ';'

      /usr/share/elasticsearch/bin/plugin install "$INSTALL_ARGS"
    fi
    ;;

  uninstall)
    if [ "$PLUGIN_INSTALLED" = "yes" ]; then
      /usr/share/elasticsearch/bin/plugin remove "$PLUGIN_NAME"
    else
      echo "$PLUGIN_NAME not installed, doing nothing"
    fi
    ;;

  *)
    echo "Unknown action provided. Use [check|install|uninstall]"
    exit 1
    ;;

esac

